stages:
- name: Deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cvblog/app:v1
      registry: 127.0.0.1:34170
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
