stages:
- name: go build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: go get encoding/json fmt html/template io/ioutil net/http
  - runScriptConfig:
      image: golang:latest
      shellScript: go build -o app .
- name: Run
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: ./app
timeout: 60
notification: {}
