stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/igresc
        ln -s `pwd` /go/src/github.com/igresc/cv-blog
        cd /go/src/github.com/igresc/cv-blog
        go build -o bin/cv
        ls -la -R
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cv-blog-server:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  exclude:
  - dev
notification:
  recipients:
  - recipient: default
    notifier: c-ljwjp:n-bm8cf
  condition:
  - Success
  - Changed
  - Failed
