stages:
- name: go build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: go get encoding/json fmt html/template io/ioutil net/http
  - runScriptConfig:
      image: golang:latest
      shellScript: go build -o app .
- name: Deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test
      registry: 127.0.0.1:34170
- name: asd
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
