stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/igresc
        ln -s `pwd` /go/src/github.com/igresc/cv-blog
        cd /go/src/github.com/igresc/cv-blog
        go build -o bin/cv
        ls -la -R
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cv-blog-server:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification:
  recipients:
  - recipient: http://discordapp.com/api/webhooks/743847179461853266/wUXoscdFy3_QYeNZxnEByTCHONp5d_6P6YYPw4msYuurpy44-cTfDAPdq4fZrRjtAXGR
    notifier: c-ljwjp:n-gltp6
  condition:
  - Success
