stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cv-blog-server:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  exclude:
  - dev
notification:
  recipients:
  - recipient: default
    notifier: c-ljwjp:n-bm8cf
  condition:
  - Success
  - Changed
  - Failed
